PKG_NAME = make
PKG_VERS = 4.3
PKG_EXT = tar.lz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://ftp.gnu.org/gnu/$(PKG_NAME)
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = 

HOMEPAGE = https://www.gnu.org/software/make/
COMMENT = GNU Make is a tool which controls the generation of executables and other non-source files of a program from the program's source files. 
LICENSE = GPL v3.0

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
