PKG_NAME = isl
PKG_VERS = 0.23
PKG_EXT = tar.xz
PKG_DIST_NAME = $(PKG_NAME)-$(PKG_VERS).$(PKG_EXT)
PKG_DIST_SITE = http://isl.gforge.inria.fr
PKG_DIR = $(PKG_NAME)-$(PKG_VERS)

DEPENDS = cross/gmp

HOMEPAGE = http://isl.gforge.inria.fr/
COMMENT = isl is a library for manipulating sets and relations of integer points bounded by linear constraints.
LICENSE = GPL v3.0

GNU_CONFIGURE = 1

include ../../mk/spksrc.cross-cc.mk
